/* eslint-disable @typescript-eslint/no-explicit-any, prefer-const */
import { bossFraction, homeostasisBand, terminalReason, tissueIntegrity, tissueState } from './simulation-rules';

export interface SemanticAxis { x:number; y:number }
export interface HomeostasisMechanicPorts {
  particle(x:number,y:number,color?:string,count?:number,speed?:number,kind?:string):void;
  audio:{kill():void;level():void};
  finish(won:boolean,reason:string):void;
}

export interface HomeostasisMechanicConfig {
  WORLD_W:number; WORLD_H:number; MAX_BACTERIA:number; PLAYER_SPEED:number;
}

export function createHomeostasisMechanics(Game:any,RNG:any,CFG:HomeostasisMechanicConfig,ports:HomeostasisMechanicPorts){
  const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));
  const dist2=(a:number,b:number,c:number,d:number)=>{const x=a-c,y=b-d;return x*x+y*y;};
  const particle=ports.particle;
  function spawnBacterium(x:number,y:number,tier=1){if(Game.bacteria.length>=CFG.MAX_BACTERIA)return null;const b={id:Math.floor(RNG.next()*1e9),x:clamp(x,20,CFG.WORLD_W-20),y:clamp(y,20,CFG.WORLD_H-20),vx:0,vy:0,r:RNG.range(8,12),hp:28+tier*8,maxHp:28+tier*8,speed:RNG.range(35,52)+tier*3,attackCd:RNG.range(.2,.8),splitCd:RNG.range(8,15),retarget:0,target:null,marked:0,slow:0,rot:RNG.range(0,Math.PI*2),variant:RNG.int(0,4),dead:false};Game.bacteria.push(b);return b;}
  function damageTissueAt(x:number,y:number,radius:number,amount:number,source='pathogen'){if(amount<=0)return 0;let dealt=0;const rr=radius*radius;for(const t of Game.tissues){if(t.debris<0||t.hp<=0)continue;const d=dist2(x,y,t.x,t.y);if(d>rr)continue;const fall=1-Math.sqrt(d)/radius;const protectedByResolve=source==='pathogen'&&Game.mode==='resolve'&&dist2(Game.player.x,Game.player.y,t.x,t.y)<=175*175;const raw=amount*fall*t.importance*(protectedByResolve?.45:1),before=t.hp;t.hp=Math.max(0,t.hp-raw);const delta=before-t.hp;if(delta<=0)continue;dealt+=delta;t.lastSource=source;if(t.hp<=0){t.debris=1;particle(t.x,t.y,'#a8686e',9,90,'debris');Game.inflammation=clamp(Game.inflammation+.008*t.importance,0,1);}if(source==='pathogen')Game.stats.pathogenDamage+=delta;else if(source==='inflammatory_injury')Game.stats.inflammatoryInjury+=delta;else if(source==='necrotic_chain')Game.stats.necroticChain+=delta;else Game.stats.directCollateral+=delta;}return dealt;}
  function repairTissueAt(x:number,y:number,radius:number,amount:number){let repaired=0,rr=radius*radius;for(const t of Game.tissues){if(t.hp<=0||t.debris<0||t.hp>=t.maxHp||dist2(x,y,t.x,t.y)>rr)continue;const d=Math.min(amount,t.maxHp-t.hp);t.hp+=d;repaired+=d;if(d>0)t.repairFx=.28;}Game.stats.repaired+=repaired;return repaired;}
  function nearestTissue(x:number,y:number,predicate=(t:any)=>t.hp>0){let best=null,bd=Infinity;for(const t of Game.tissues){if(!predicate(t))continue;const d=dist2(x,y,t.x,t.y);if(d<bd){bd=d;best=t;}}return best;}
  function updateTissue(dt:number){const eff=Game.upgrades.efferocytosis||0,plate=Game.upgrades.platelet||0;if(Game.mode==='resolve'&&eff>0)for(const t of Game.tissues){if(t.hp>0||t.debris<=0||dist2(Game.player.x,Game.player.y,t.x,t.y)>(145+eff*25)**2)continue;t.debris-=dt*(.12+.07*eff);Game.inflammation=Math.max(0,Game.inflammation-dt*.004*eff);if(t.debris<=0){t.debris=-1;particle(t.x,t.y,'#8de1c1',12,55,'resolve');Game.xp+=2;}}if(Game.mode==='resolve')repairTissueAt(Game.player.x,Game.player.y,175,dt*4.5);if(plate>0)repairTissueAt(Game.player.x,Game.player.y,125+plate*18,dt*(Game.mode==='resolve'?5.2:1.1)*plate);for(const t of Game.tissues){t.repairFx=Math.max(0,(t.repairFx||0)-dt);t.state=tissueState(t);}}
  function nearestEnemy(x:number,y:number,range=Infinity){let best=null,bd=range*range;for(const b of Game.bacteria){if(b.dead)continue;const d=dist2(x,y,b.x,b.y);if(d<bd){bd=d;best=b;}}if(Game.boss&&!Game.boss.dead){const d=dist2(x,y,Game.boss.x,Game.boss.y);if(d<bd){best=Game.boss;best.isBoss=true;}}return best;}
  function dealDamage(target:any,amount:number){if(!target||amount<=0)return;if(target===Game.boss||target.isBoss){const b=Game.boss;b.hitFx=.12;if(b.matrixHp>0)b.matrixHp=Math.max(0,b.matrixHp-amount);else b.coreHp=Math.max(0,b.coreHp-amount);particle(b.x+RNG.range(-35,35),b.y+RNG.range(-35,35),b.matrixHp>0?'#80d1ae':'#ffbb71',3,60);if(b.coreHp<=0&&!b.dead){b.dead=true;particle(b.x,b.y,'#baffce',34,180,'burst');ports.audio.level();}return;}const markBonus=target.marked>0?1.25+.1*(Game.upgrades.complement||0):1;target.hp-=amount*markBonus;if(target.hp<=0&&!target.dead){target.dead=true;Game.stats.kills++;Game.pickups.push({x:target.x,y:target.y,vx:0,vy:0,value:5,ttl:20});particle(target.x,target.y,'#ffd36b',10,120,'burst');ports.audio.kill();}}
  function updatePlayer(dt:number,a:SemanticAxis){const p=Game.player;p.vx=a.x*CFG.PLAYER_SPEED;p.vy=a.y*CFG.PLAYER_SPEED;p.x=clamp(p.x+p.vx*dt,p.r,CFG.WORLD_W-p.r);p.y=clamp(p.y+p.vy*dt,p.r,CFG.WORLD_H-p.r);p.attackCd-=dt;p.attackFx=Math.max(0,p.attackFx-dt);p.hitFx=Math.max(0,p.hitFx-dt);if(Game.mode==='engage'&&p.attackCd<=0){const reach=Game.upgrades.phagocyticReach||0,target=nearestEnemy(p.x,p.y,135+reach*28);if(target){const treg=Game.upgrades.treg||0;p.attackCd=(.47-reach*.025)*(1+treg*.08);p.attackFx=.16;p.attackTarget=target;dealDamage(target,15+reach*5);damageTissueAt(target.x,target.y,34+reach*4,Math.max(.35,1.2+reach*.75),'phagocytosis');Game.inflammation=clamp(Game.inflammation+.0032+reach*.0012,0,1);}}for(const b of Game.bacteria){if(b.dead)continue;const rr=p.r+b.r+2;if(dist2(p.x,p.y,b.x,b.y)<rr*rr){p.hp=Math.max(0,p.hp-dt*7);p.hitFx=.15;const dx=p.x-b.x,dy=p.y-b.y,m=Math.hypot(dx,dy)||1;p.x+=dx/m*35*dt;p.y+=dy/m*35*dt;}}}
  function ensureNeutrophils(){const target=(Game.upgrades.neutrophils||0)*2;while(Game.neutrophils.length<target)Game.neutrophils.push({angle:RNG.range(0,Math.PI*2),cooldown:RNG.range(0,.8),x:Game.player.x,y:Game.player.y,flash:0});while(Game.neutrophils.length>target)Game.neutrophils.pop();}
  function updateNeutrophils(dt:number){ensureNeutrophils();const chem=Game.upgrades.chemotaxis||0;for(let i=0;i<Game.neutrophils.length;i++){const n=Game.neutrophils[i];n.angle+=dt*(1.6+i*.08);n.x=Game.player.x+Math.cos(n.angle)*(42+i%2*12);n.y=Game.player.y+Math.sin(n.angle)*(42+i%2*12);n.cooldown-=dt;n.flash=Math.max(0,n.flash-dt);if(Game.mode==='engage'&&n.cooldown<=0){const t=nearestEnemy(n.x,n.y,280+chem*35);if(t){n.cooldown=1.15-chem*.08;n.flash=.13;dealDamage(t,10+(Game.upgrades.neutrophils||0)*3);damageTissueAt(t.x,t.y,48,Math.max(.5,6-chem*1.7),'neutrophil');Game.inflammation=clamp(Game.inflammation+.0055-chem*.0008,0,1);particle(t.x,t.y,'#f4f3cf',7,100,'burst');}}}}
  function updateComplement(dt:number){const tier=Game.upgrades.complement||0;if(!tier||Game.mode!=='engage')return;Game.complementTimer-=dt;if(Game.complementTimer>0)return;Game.complementTimer=Math.max(.55,1.7-tier*.18);const candidates=Game.bacteria.filter((b:any)=>!b.dead&&dist2(Game.player.x,Game.player.y,b.x,b.y)<330*330);for(let i=0;i<Math.min(tier+1,candidates.length);i++){const b=candidates[RNG.int(0,candidates.length-1)];b.marked=Math.max(b.marked,3+tier);dealDamage(b,2+tier);particle(b.x,b.y,'#74f7cd',5,45,'ring');if(Game.inflammation>Game.safeHigh){damageTissueAt(b.x,b.y,58,2.2*tier,'complement_spillover');Game.inflammation=clamp(Game.inflammation+.004*tier,0,1);}}}
  function updateAntibodies(dt:number){const tier=Game.upgrades.antibody||0;if(!tier||Game.mode!=='engage')return;Game.antibodyTimer-=dt;if(Game.antibodyTimer>0)return;Game.antibodyTimer=Math.max(.45,1.45-tier*.16);const target=nearestEnemy(Game.player.x,Game.player.y,390);if(target&&target!==Game.boss)Game.antibodies.push({x:Game.player.x,y:Game.player.y,target,speed:250,ttl:2.5,tier,rot:0});}
  function updateAntibodyProjectiles(dt:number){for(let i=Game.antibodies.length-1;i>=0;i--){const a=Game.antibodies[i];a.ttl-=dt;if(a.ttl<=0||!a.target||a.target.dead){Game.antibodies.splice(i,1);continue;}const dx=a.target.x-a.x,dy=a.target.y-a.y,m=Math.hypot(dx,dy)||1;a.x+=dx/m*a.speed*dt;a.y+=dy/m*a.speed*dt;a.rot+=dt*8;if(m<13){a.target.marked=Math.max(a.target.marked,4+a.tier);a.target.slow=Math.max(a.target.slow,3+a.tier);dealDamage(a.target,2+a.tier);particle(a.x,a.y,'#a4d7ff',5,45,'ring');Game.antibodies.splice(i,1);}}}
  function updateBacteria(dt:number){const under=Math.max(0,Game.safeLow-Game.inflammation),survivors:any[]=[],births:any[]=[];for(const b of Game.bacteria){if(b.dead)continue;b.marked=Math.max(0,b.marked-dt);b.slow=Math.max(0,b.slow-dt);b.retarget-=dt;b.attackCd-=dt;b.splitCd-=dt;b.rot+=dt*.8;if(!b.target||b.target.hp<=0||b.target.debris<0||b.retarget<=0){b.target=nearestTissue(b.x,b.y);b.retarget=RNG.range(.7,1.5);}const t=b.target;if(t){const dx=t.x-b.x,dy=t.y-b.y,m=Math.hypot(dx,dy)||1,s=b.speed*(b.slow>0?.62:1);if(m>t.r*.62){b.x+=dx/m*s*dt;b.y+=dy/m*s*dt;}else if(b.attackCd<=0){b.attackCd=.55;damageTissueAt(b.x,b.y,38,4.4+Game.stage*.35,'pathogen');Game.inflammation=clamp(Game.inflammation+.0015,0,1);}}if(b.splitCd<=0&&under>.015&&survivors.length+births.length<Game.bacteria.length+8&&Game.bacteria.length+births.length<CFG.MAX_BACTERIA){b.splitCd=RNG.range(9,15)/(1+under*4);if(RNG.next()<clamp(.18+under*2.2,0,.78))births.push({x:b.x+RNG.range(-18,18),y:b.y+RNG.range(-18,18),tier:1+Game.stage*.25});}survivors.push(b);}Game.bacteria=survivors;for(const born of births)spawnBacterium(born.x,born.y,born.tier);}
  function updateBoss(dt:number){const b=Game.boss;if(!b||b.dead)return;b.hitFx=Math.max(0,b.hitFx-dt);b.spawnCd-=dt;b.toxinCd-=dt;if(b.spawnCd<=0){b.spawnCd=Math.max(1.7,4.6-Game.stage*.38);for(let i=0;i<2+Math.min(4,Game.stage);i++){const a=RNG.range(0,Math.PI*2),rr=RNG.range(68,100);spawnBacterium(b.x+Math.cos(a)*rr,b.y+Math.sin(a)*rr,1+Game.stage*.3);}}if(b.toxinCd<=0){b.toxinCd=Math.max(4.5,8-Game.stage*.45);Game.inflammation=clamp(Game.inflammation+.018,0,1);damageTissueAt(b.x,b.y,170,4.5,'pathogen');particle(b.x,b.y,'#ff7e78',20,120,'toxin');}}
  function updatePickups(dt:number){for(let i=Game.pickups.length-1;i>=0;i--){const p=Game.pickups[i];p.ttl-=dt;if(p.ttl<=0){Game.pickups.splice(i,1);continue;}const dx=Game.player.x-p.x,dy=Game.player.y-p.y,m=Math.hypot(dx,dy)||1;if(m<170){p.vx+=dx/m*420*dt;p.vy+=dy/m*420*dt;}p.vx*=.94;p.vy*=.94;p.x+=p.vx*dt;p.y+=p.vy*dt;if(m<26){Game.xp+=p.value;particle(p.x,p.y,'#d5ff8e',6,80);Game.pickups.splice(i,1);}}}
  function updateHomeostasis(dt:number){const enemyLoad=clamp(Game.bacteria.length/150,0,1),bossLoad=bossFraction(Game.boss);Game.pathogenLoad=clamp(enemyLoad*.58+bossLoad*.42,0,1);({safeLow:Game.safeLow,safeHigh:Game.safeHigh}=homeostasisBand(Game.pathogenLoad));const treg=Game.upgrades.treg||0,deadCount=Game.tissues.reduce((n:number,t:any)=>n+(t.hp<=0&&t.debris>=0?1:0),0),dangerGain=deadCount*.0000045,decay=Game.mode==='resolve'?(.22+treg*.03):(.006+treg*.0045);Game.inflammation=clamp(Game.inflammation+(dangerGain-decay)*dt,0,1);const over=Math.max(0,Game.inflammation-Game.safeHigh),under=Math.max(0,Game.safeLow-Game.inflammation);if(over>0){if(Game.mode==='resolve')Game.camera.shake=0;else{Game.camera.shake=Math.max(Game.camera.shake,over*10);damageTissueAt(Game.player.x,Game.player.y,150+over*140,dt*over*19,'inflammatory_injury');if(Game.inflammation>.88)Game.stats.stormSeconds+=dt;}}if(deadCount>0&&RNG.next()<deadCount*dt*.002){const dead=RNG.pick(Game.tissues.filter((t:any)=>t.hp<=0&&t.debris>=0));if(dead)damageTissueAt(dead.x,dead.y,90,1.5,'necrotic_chain');}if(under>.02&&Game.bacteria.length>0)Game.infectionMaxTime+=dt*under;else Game.infectionMaxTime=Math.max(0,Game.infectionMaxTime-dt*.5);Game.tissueIntegrity=tissueIntegrity(Game.tissues);Game.stats.peakInflammation=Math.max(Game.stats.peakInflammation,Game.inflammation);if(Game.inflammation>.97&&Game.mode!=='resolve')Game.stormTime+=dt;else Game.stormTime=Math.max(0,Game.stormTime-dt*1.4);const stable=Game.boss.dead&&Game.bacteria.length<=3&&Game.inflammation>=Game.safeLow&&Game.inflammation<=Game.safeHigh;Game.resolveHold=stable?Game.resolveHold+dt:Math.max(0,Game.resolveHold-dt*.8);const terminal=terminalReason(Game);if(terminal)ports.finish(terminal.won,terminal.reason);}
  function updateDirector(dt:number){if(Game.boss.dead)return;Game.spawnTimer-=dt;if(Game.spawnTimer<=0){Game.spawnTimer=Math.max(1.8,5.2-Game.stage*.45);const side=RNG.int(0,3),x=side===0?50:side===1?CFG.WORLD_W-50:RNG.range(80,CFG.WORLD_W-80),y=side===2?50:side===3?CFG.WORLD_H-50:RNG.range(80,CFG.WORLD_H-80);for(let i=0;i<1+Math.floor(Game.stage/2);i++)spawnBacterium(x+RNG.range(-35,35),y+RNG.range(-35,35),1+Game.stage*.25);}}
  function updateParticles(dt:number){for(const p of Game.particles)if(p.active){p.ttl-=dt;if(p.ttl<=0){p.active=false;continue;}p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.96;p.vy*=.96;}}
  function drawUpgradeChoices(defs:any[]){const pool=defs.filter(d=>(Game.upgrades[d.id]||0)<3),out=[];while(pool.length&&out.length<3)out.push(pool.splice(RNG.int(0,pool.length-1),1)[0]);return out;}
  function chooseUpgrade(id:string){Game.upgrades[id]=(Game.upgrades[id]||0)+1;Game.scene='play';}
  return {spawnBacterium,damageTissueAt,repairTissueAt,updateTissue,updatePlayer,updateNeutrophils,updateComplement,updateAntibodies,updateAntibodyProjectiles,updateBacteria,updateBoss,updatePickups,updateHomeostasis,updateDirector,updateParticles,drawUpgradeChoices,chooseUpgrade};
}
